### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by juliusr91**
Hi Elia,
thanks a lot for the library!
Would you mind adding a license to the project? 
I would like to suggest the MIT license - it allows:  Commercial use, Distribution, Modification, Private use and you are not hold liable for any problems. 
Here is a nice overview of the license: https://choosealicense.com/licenses/mit/
Thank you, 
Julius

### CODE REVIEW

**Comment by drashna** [comment]
The GPL3 license would also work for that, and I think it would work better.

**Comment by g4lvanix** [comment]
Hello Julius and drashna I have added a LICENSE file. The code is now licensed as GPLv3. 

Thank you for pushing me to add this license after years. :)

**Comment by drashna** [comment]
Awesome!  Thank you very much!  We very much appreciate this!

**Comment by juliusr91** [comment]
Thanks a lot :)

**Pull request closed without merging**
